---
roles:
  - name: palekiwi.dotfiles
    src: https://github.com/palekiwi/ansible-role-dotfiles
    version: main

  - name: palekiwi.security_general
    src: https://github.com/palekiwi/ansible-role-security_general
    version: main
