---
dotfiles_repo: git@github.com:palekiwi/dotfiles
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true

dotfiles_files:
  - { label: "ansible.inventory", dest: "~/.inventory.ini", src: "fedora/ansible/inventory.ini" }
  - { label: "ansible.config", dest: "~/.ansible.cfg", src: "fedora/ansible/ansible.cfg" }
  - { label: "awesome.autostart", dest: "~/.config/awesome/autostart.sh", src: "fedora/config/awesome/{{ ansible_hostname }}.autostart.sh" }
  - { label: "awesome.clientbuttons", dest: "~/.config/awesome/clientbuttons.lua", src: "fedora/config/awesome/clientbuttons.lua" }
  - { label: "awesome.clientkeys", dest: "~/.config/awesome/clientkeys.lua", src: "fedora/config/awesome/clientkeys.lua" }
  - { label: "awesome.globalkeys", dest: "~/.config/awesome/globalkeys.lua", src: "fedora/config/awesome/globalkeys.lua" }
  - { label: "awesome.globals", dest: "~/.config/awesome/globals.lua", src: "fedora/config/awesome/globals.lua" }
  - { label: "awesome.luarc", dest: "~/.config/awesome/.luarc.json", src: "fedora/config/awesome/luarc.json" }
  - { label: "awesome.rc", dest: "~/.config/awesome/rc.lua", src: "fedora/config/awesome/rc.lua" }
  - { label: "awesome.rules", dest: "~/.config/awesome/rules.lua", src: "fedora/config/awesome/rules.lua" }
  - { label: "awesome.signals", dest: "~/.config/awesome/signals.lua", src: "fedora/config/awesome/signals.lua" }
  - { label: "awesome.tags", dest: "~/.config/awesome/tags.lua", src: "fedora/config/awesome/tags.lua" }
  - { label: "awesome.theme", dest: "~/.config/awesome/theme.lua", src: "fedora/config/awesome/theme.lua" }
  - { label: "awesome.wibar", dest: "~/.config/awesome/wibar.lua", src: "fedora/config/awesome/wibar.lua" }
  - { label: "awesome.widgets", dest: "~/.config/awesome/widgets", src: "fedora/config/awesome/widgets" }
  - { label: "bash_aliases", dest: "~/.bash_aliases", src: "fedora/bash_aliases" }
  - { label: "bashenv", dest: "~/.bashenv", src: "fedora/bashenv" }
  - { label: "bashrc", dest: "~/.bashrc", src: "fedora/bashrc" }
  - { label: "dmenu.dir", dest: "~/.dmenu/dir", src: "fedora/dmenu/dmenu_dir.sh" }
  - { label: "dmenu.dotfiles", dest: "~/.dmenu/dotfiles", src: "fedora/dmenu/dmenu_dotfiles.sh" }
  - { label: "dmenu.keybindings", dest: "~/.dmenu/keybindings", src: "fedora/dmenu/dmenu_sxhkd.sh" }
  - { label: "dmenu.mindmaps", dest: "~/.dmenu/mindmaps", src: "fedora/dmenu/dmenu_mindmaps.sh" }
  - { label: "dmenu.process", dest: "~/.dmenu/process", src: "fedora/dmenu/dmenu_process.sh" }
  - { label: "dmenu.quit", dest: "~/.dmenu/quit", src: "fedora/dmenu/dmenu_quit.sh" }
  - { label: "dmenu.repos", dest: "~/.dmenu/repos", src: "fedora/dmenu/dmenu_repos.sh" }
  - { label: "dmenu.sys", dest: "~/.dmenu/sys", src: "fedora/dmenu/dmenu_sys.sh" }
  - { label: "dmenu.xrandr", dest: "~/.dmenu/xrandr", src: "fedora/dmenu/dmenu_xrandr.sh" }
  - { label: "gpg-agent", dest: "~/.gnupg/gpg-agent.conf", src: "fedora/gpg-agent.conf" }
  - { label: "mimeapps", dest: "~/.config/mimeapps.list", src: "fedora/config/mimeapps.list" }
  - { label: "picom.conf", dest: "~/.config/picom/picom.conf", src: "fedora/config/picom/picom.conf" }
  - { label: "sxhkdrc", dest: "~/.config/sxhkd/sxhkdrc", src: "fedora/config/sxhkd/sxhkdrc" }
  - { label: "sxhkdrc.blender", dest: "~/.config/sxhkd/blender.sxhkdrc", src: "fedora/config/sxhkd/blender.sxhkdrc" }
  - { label: "sxhkdrc.comfyui", dest: "~/.config/sxhkd/comfyui.sxhkdrc", src: "fedora/config/sxhkd/comfyui.sxhkdrc" }
  - { label: "sxhkdrc.dmenu", dest: "~/.config/sxhkd/dmenu.sxhkdrc", src: "fedora/config/sxhkd/dmenu.sxhkdrc" }
  - { label: "terminal.rc", dest: "~/.config/xfce4/terminal/terminalrc", src: "fedora/config/xfce4/terminal/{{ ansible_hostname }}.terminalrc" }
  - { label: "terminal.theme", dest: "~/.config/xfce4/terminal/colorschemes/arc.theme", src: "fedora/config/xfce4/terminal/colorschemes/arc.theme" }
  - { label: "xmodmap", dest: "~/.Xmodmap", src: "fedora/{{ ansible_hostname }}.Xmodmap" }

dotfiles_extra_repos:
  - repo: "https://github.com/lcpz/lain.git"
    dest: "~/.config/awesome/lain"
    version: "master"
