---
flatpak_packages:
  - { state: present, method: user, remote: flathub, filesystem: home, name: com.google.Chrome }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.gimp.GIMP }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.goldendict.GoldenDict }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.inkscape.Inkscape }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.kde.okular }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.mozilla.Thunderbird }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.signal.Signal }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.videolan.VLC }
