---
flatpak_packages:
  - { state: present, method: user, remote: flathub, filesystem: home, name: com.google.Chrome }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.gimp.GIMP }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.kde.okular }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.mozilla.firefox }
  - { state: present, method: user, remote: flathub, filesystem: home, name: org.videolan.VLC }
  - { state: present, method: user, remote: flathub, name: org.pulseaudio.pavucontrol}
