---
ostree_packages:
  - awesome
  - distrobox
  - dmenu
  - kitty
  - pam-u2f
  - pamu2fcfg
  - picom
  - pulseaudio-utils
  - sxhkd
  - tailscale
  - xfce4-terminal
  - xrandr
  - xscreensaver
  - zsh
