---
- name: Ensure model dirs exist.
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop: "{{ comfyui_models }}"
  loop_control:
    label: "{{ item.dir }}"

- name: Install templates.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: templates/extra_model_path.yaml.j2
      dest: "{{ comfyui_dir }}/extra_model_paths.yaml"
  loop_control:
    label: "{{ item.dest }}"
