---
- name: Install ComfyUI.
  hosts: ctn

  vars:
    ansible_user: pl
    comfyui_venv: ~/.venv/fedora/sd-gui
    comfyui_repo: https://github.com/comfyanonymous/ComfyUI
    comfyui_dir: ~/opt/comfy-ui
    comfyui_models:
      - key: checkpoints
        value: /opt/models/checkpoints/
      - key: vae
        value: /opt/models/vae/

  tasks:
    - name: Ensure repos have been cloned.
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        depth: 1
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      loop:
        - repo: "{{ comfyui_repo }}"
          dest: "{{ comfyui_dir }}"
          version: master
        - repo: https://github.com/ltdrdata/ComfyUI-Manager.git
          dest: "{{ comfyui_dir }}/custom_nodes/ComfyUI-Manager"
          version: main

    - name: Install templates.
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: templates/extra_model_path.yaml.j2
          dest: "{{ comfyui_dir }}/extra_model_paths.yaml"

    - name: Ensure packages are installed.
      ansible.builtin.pip:
        virtualenv: "{{ comfyui_venv }}"
        virtualenv_command: /usr/bin/python -m venv
        name:
          - torch
          - torchvision
          - torchaudio
        extra_args: "--extra-index-url https://download.pytorch.org/whl/cu121"

    - name: Install specified python requirements
      ansible.builtin.pip:
        virtualenv: "{{ comfyui_venv }}"
        virtualenv_command: /usr/bin/python -m venv
        requirements: "{{ comfyui_dir }}/requirements.txt"
