---
- name: Configure mounts on workstation.
  hosts: workstation
  become: true

  tasks:
    - name: Set facts.
      ansible.builtin.set_fact:
        mount_crypttab: "{{ mount_crypttab + mount_crypttab_host }}"
        mount_fstab: "{{ mount_fstab + mount_fstab_host }}"

    - name: Set up cryptab.
      community.general.crypttab:
        name: "{{ item.name }}"
        backing_device: "{{ item.backing_device }}"
        password: "{{ item.password | default(omit) }}"
        opts: "{{ item.opts }}"
        state: "{{ item.state }}"
      loop: "{{ mount_crypttab }}"

    - name: Ensure mount directories exist.
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"
      loop: "{{ mount_fstab }}"

    - name: Setup up fstab mounts.
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        boot: "{{ item.boot | default(omit) }}"
        state: "{{ item.state }}"
      loop: "{{ mount_fstab }}"
