---
- name: Manage rpm-ostree.
  hosts: workstation

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: ./handlers/main.yml

  tasks:
    - name: Ensure packages are installed.
      when: false
      community.general.rpm_ostree_pkg:
        name: "{{ ostree_packages }}"
        state: present
      notify: Require reboot.
