---
- name: Disable pcspkr.
  hosts: workstation
  become: true

  tasks:
    - name: Blacklist pcspkr
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/nobeep.conf
        line: "blacklist pcspkr"
        create: true
        mode: "0644"
